db = connect("localhost/csm");
db.placeAddresses.remove({});
db.placeAddresses.insert({ _id : NumberLong(1), street : "Шевченка", street_type : "STREET"});
db.placeAddresses.insert({ _id : NumberLong(2), street : "Лесі Українки", street_type : "STREET"});
db.placeAddresses.insert({ _id : NumberLong(3), street : "Івана Франка", street_type : "STREET"});
db.placeAddresses.insert({ _id : NumberLong(4), street : "Івана Мазепи", street_type : "STREET"});
db.placeAddresses.insert({ _id : NumberLong(5), street : "Степана Бандери", street_type : "STREET"});
db.placeAddresses.insert({ _id : NumberLong(6), street : "Шевченка", street_type : "LANE"});
db.placeAddresses.insert({ _id : NumberLong(7), street : "Лесі Українки", street_type : "LANE"});
db.placeAddresses.insert({ _id : NumberLong(8), street : "Івана Франка", street_type : "LANE"});
db.placeAddresses.insert({ _id : NumberLong(9), street : "Івана Мазепи", street_type : "LANE"});
db.placeAddresses.insert({ _id : NumberLong(10), street : "Степана Бандери", street_type : "LANE"});
db.placeAddresses.insert({ _id : NumberLong(11), street : "Українська", street_type : "STREET"});
db.placeAddresses.insert({ _id : NumberLong(12), street : "Український", street_type : "LANE"});